name: Generate Changelogs
run-name: 'chore(release): generate changelogs for ${{ inputs.previous_release_tag }}..${{ inputs.future_release_tag }}'

on:
  workflow_dispatch:
    inputs:
      previous_release_tag:
        required: true
        description: previous release tag
      future_release_tag:
        required: true
        description: future release tag

jobs:
  build:
    name: Generate changelogs
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: latest

      - run: node scripts/generate-changelog.mjs
        env:
          PREVIOUS_TAG: ${{ inputs.previous_release_tag }}
          FUTURE_TAG: ${{ inputs.future_release_tag }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_ID: ${{ github.run_id }}
